// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ3kjopkibf4th5gL9O8OgrFioNi528mk',
    appId: '1:681257160922:web:b05890852337e7d82f15e3',
    messagingSenderId: '681257160922',
    projectId: 'class-project-f1516',
    authDomain: 'class-project-f1516.firebaseapp.com',
    storageBucket: 'class-project-f1516.appspot.com',
    measurementId: 'G-59V7VBXNWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpkV6hZpfVURYB2QHqZ032bnd-v2R3LI',
    appId: '1:681257160922:android:1421faef625161be2f15e3',
    messagingSenderId: '681257160922',
    projectId: 'class-project-f1516',
    storageBucket: 'class-project-f1516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCutHombz9CFzbOXhQz_fdWgTZ7Ou9Rpcc',
    appId: '1:681257160922:ios:7de0b4439d2728882f15e3',
    messagingSenderId: '681257160922',
    projectId: 'class-project-f1516',
    storageBucket: 'class-project-f1516.appspot.com',
    iosBundleId: 'com.example.classProject',
  );
}
